### ISSUE TITLE
Checking Master Status

### ISSUE THREAD

**Issue by therussiankid92** [myzhan/locust4j#13]
Hi there,

Good job on the library! 
I'm trying to understand if you currently have any exposed way that you are checking that:
- master is up and ready to be connected
- slave is connected to master

Cheers!

**Comment by myzhan** [comment]
Sorry, currently there is not way to check the connnection status. Maybe it is better to add an entry at master. You can check this out https://github.com/myzhan/boomer/blob/master/prometheus_exporter.py

**Comment by therussiankid92** [comment]
Thanks! Do you mean to add the configuration in the .py file?

**Comment by myzhan** [comment]
You need to write some code in a .py file to expose the internal status of the master. Then you can start a locust master with the .py file.
