### ISSUE TITLE
Analysing Locust4j - Performance test

### ISSUE THREAD

**Issue by sirisha-potluri** [myzhan/locust4j#17]
I'm exploring Locust for performance test our applications. Would like to reuse the existing Java page objects(selenium web elements) instead of rewriting in Python.
Issue: I try to invoke a particular count of users, by entering in the textbox "Number of total users to simulate" (on the locust ui) but actually runs into an infinite loop spawning users forever.
1. How do I control the no. of requests.
2. Is this a right approach, where I'm trying to fire Selenium events instead of http get/post requests
Attaching the code snippet
[testcode.TXT](https://github.com/myzhan/locust4j/files/4638889/testcode.TXT)

Thanks,
Sirisha

**Comment by myzhan** [comment]
Because the "execute" method runs in an infinite loop, you can't control the number of requests. Instead, you have control of thread-concurency and request per second(aka RPS).

If you really want to control the number of requests, try to keep a counter of requests and do nothing but sleeping in the "execute" method when the threshold exceeded.

**Comment by myzhan** [comment]
BTW, performance testing using Selenium and WebDriver is generally not advised.

See aslo, https://www.selenium.dev/documentation/en/worst_practices/performance_testing/

**Comment by sirisha-potluri** [comment]
> Because the "execute" method runs in an infinite loop, you can't control the number of requests. Instead, you have control of thread-concurency and request per second(aka RPS).
> 
> If you really want to control the number of requests, try to keep a counter of requests and do nothing but sleeping in the "execute" method when the threshold exceeded.
Thanks for the quick response!
We also have developed a prototype in python for firing selenium events. But in python, there seems to be no problem as The no. of users input on the locust UI spins up exactly the sam
[locustfile_python.TXT](https://github.com/myzhan/locust4j/files/4645852/locustfile_python.TXT)
e count of browsers through selenium. How is it controlled in Python. 
Attaching the code for reference.
