### ISSUE TITLE
How to get target website url field in locust4j

### ISSUE THREAD

**Issue by Tonghua-Li** [myzhan/locust4j#19]
In python version, user can specify which website to test, how to get that field in locust4j?
Thanks
![image](https://user-images.githubusercontent.com/1747556/85312852-6a94ad00-b485-11ea-9ccf-e76a086b5845.png)

**Comment by myzhan** [comment]
Adding a new API to support this.
https://github.com/myzhan/locust4j/commit/9679d7f152a12667c2da75628ef61b7410d09e84

**Comment by myzhan** [comment]
Try version 1.0.11, a new API is added.
