### ISSUE TITLE
wait_time support

### ISSUE THREAD

**Issue by vilkg** [myzhan/locust4j#29]
Hey! 

Does locust4j support waiting between tasks? An equivalent to `wait_time = between(1000, 3000)` that's supported by locust?

**Comment by myzhan** [comment]
Not supported currently, you can call Thread.sleep in your task.

**Comment by vilkg** [comment]
Thanks, was wondering if there's a more elegant way that doesn't require recompiling the project to change the value. Could you plase deploy master? I see that AbstractTask has new methods which could be helpful for that.

**Comment by myzhan** [comment]
OK, I will find some time to release the master branch.

**Comment by myzhan** [comment]
Version 1.0.13 has been released.
