### ISSUE TITLE
recordFailure does not record as a request

### ISSUE THREAD

**Issue by crichardson32** [myzhan/locust4j#38]
I noticed that when an error is recorded it does not also record as a request causing the rps to be less than expected. 

Both the python client and boomer appear to record errors also as requests however locust4j does not. I believe the difference is here

In boomer a record failure and request are done
https://github.com/myzhan/boomer/blob/e17d364d020f6feae49a06c05f02b19c6dcc6a5e/stats.go#L142-L144

In locust4j only the error is logged
https://github.com/myzhan/locust4j/blob/1.0.12/src/main/java/com/github/myzhan/locust4j/stats/Stats.java#L138-L142

**Comment by myzhan** [comment]
Yes, your PR is welcome.

**Comment by crichardson32** [comment]
this will fix the issue https://github.com/myzhan/locust4j/pull/39

**Comment by myzhan** [comment]
Version 2.2.1 has been released.
