### ISSUE TITLE
ack message from master not supported

### ISSUE THREAD

**Issue by dometec** [myzhan/locust4j#40]
As the log says:
 _2022-08-30 12:45:28,904 ERROR [com.git.myz.loc.run.Runner] (Thread-54receive-from-client) Got ack message from master, which is not supported, please report an issue to locust4j._

I use Locust 2.11.1, when the client connection is established with the master, on master log I see:

_[2022-08-30 12:45:28,900] localhost.localdomain/WARNING/locust.runners: A worker (localhost.localdomain_f83b72ddd1e9ba171d0fe4063ab2a0b5) running a different version (-1) connected, master version is 2.11.1_

**Comment by myzhan** [comment]
OK, working on it.

**Comment by nitinv0078** [comment]
I am getting same issue with locust 2.16.1 2023-09-22T14:22:56.795+10:00 ERROR 91396 --- [ive-from-client] c.github.myzhan.locust4j.runtime.Runner  : Got ack message from master, which is not supported, please report an issue to locust4j.

**Comment by myzhan** [comment]
OK, I just released the master branch as version 2.2.2, please give it a try.

**Comment by nitinv0078** [comment]
thank you so much that resolved the issue for me
