### ISSUE TITLE
Got heartbeat message from master, which is not supported.

### ISSUE THREAD

**Issue by Nilamber01** [myzhan/locust4j#42]
The error log appears : 
"Got heartbeat message from master, which is not supported, please report an issue to locust4j."
when the worker node is connected to master, 
version : 2.2.2

**Comment by myzhan** [comment]
It's just a warning, fixed https://github.com/myzhan/locust4j/commit/476e1cabd287bcea3dafb1014deda540e8697d54.

Please wait for a new version.

**Comment by Nilamber01** [comment]
may i ask when do you plan to release the new version ? the message is quite annoying and mixes up with the test logs.

**Comment by myzhan** [comment]
Try 2.2.3
