### ISSUE TITLE
System.exit() called

### ISSUE THREAD

**Issue by 8altazar** [myzhan/locust4j#7]
I would like to do full automated performance test with csv results analysis (asseration) in java and report generated for example in allure tool.
Problem is: after load testing (locust --run-time reached) in **Runner.java** (line 228) `System.exit(0)` is called.

**Comment by myzhan** [comment]
Because the locust master exits. What do you need?

**Comment by 8altazar** [comment]
Eg. add some field in Locust.java ` private boolean exitEnabled;` with default value true and method with possibilty to change it. What do you think about it?

**Comment by myzhan** [comment]
It's not necessary, what do you want to do if it doesn't exit?

**Comment by 8altazar** [comment]
Read locust csv results, do some asseration and generate report junit/allure. All with one command `mvn test`.

**Comment by myzhan** [comment]
What about put all the code into another tool? Or you can add a shutdown hook by calling Runtime.getRuntime().addShutdownHook()

**Comment by 8altazar** [comment]
Yes, i have to find some workaround.

**Comment by myzhan** [comment]
If you use locust4j as a plugin in maven, calling System.exit() may exit maven itself. But maven is not a suitable environment to run locust4j, jenkins may be better.
