### ISSUE TITLE
Setup the Slave Report Interval

### ISSUE THREAD

**Issue by dmarcas** [myzhan/locust4j#8]
I would like to change the slave interval for the reporting but, if I'm not wrong, this a private constant inside the StatsTimer class. Is there any way to change this value?

**Comment by myzhan** [comment]
Why do you want to change the interval? It's the default value of locust.

**Comment by dmarcas** [comment]
I want to retrieve slave results every 1 second. The default in locust is 2 seconds and I think that it would be great to get this option opened. In my case I want to ensure that if something goes wrong I have the latest results registered in my csv.

**Comment by myzhan** [comment]
The default value of Locust is 3 seconds. [Code](https://github.com/locustio/locust/blob/master/locust/runners.py#L27)

It will be great if you can dig into this and send me a PR.

**Comment by dmarcas** [comment]
Hey, your'e right is 3 (sorry). 

I'll dig into this in order to send you the PR! 

Thanks!
